name: Build Index
on: 
  push:
    branches:
      - master

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: yarn
      working-directory: ./viewer
    - run: yarn build-index
      working-directory: ./viewer
    - run: yarn build-front
      working-directory: ./viewer
    - uses: actions/upload-artifact@v2
      with:
        name: index
        path: viewer/public